### ISSUE TITLE
Table formatting is unpleasant at max-width 700px

### ISSUE THREAD

**Issue by krokofant** [noatpad/typora-theme-ursine#33]
I agree on the stylistic choice for keeping the editor small (#25) but this can easily look bad for tables (_which are intended to display data..._).

The columns can't be especially wide at all before the columns start collapsing.
![image](https://user-images.githubusercontent.com/5908498/63154547-28067680-c011-11e9-8347-18f8a27504f8.png)

max-width: 1000px
![image](https://user-images.githubusercontent.com/5908498/63154681-76b41080-c011-11e9-9f06-68b2410d2733.png)

Could we make it look okay excluding the table from the current max-width?

**Comment by aCluelessDanny** [comment]
Mmm, thing is that if I remove the `max-width` of tables, they could be instead too big, especially if the app is in full-screen mode. Increasing the `max-width` would make more sense to me, like the example you've shown by increasing just that. The `max-width: 1000px` actually plays really nicely with tables, so I'd go with that.

But there is a bit of a problem because of how elements are structured in Typora. In the app, every paragraph, header, table, etc. are in a `#write` container, which is the one in charge of setting the `width` and `max-width`, thus affecting every element. There are probably ways around that for a single child, but I might have to change from a single parent having those properties to every child those properties instead, which could bring up other problems, but we'll see.

**Comment by krokofant** [comment]
@aCluelessDanny Should we just close this? 🙂 Sizing every child element to work around table sizes doesn't seem like an ideal solution.
